routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});
Route::group(['prefix'=>'yonetim','middleware' =>'admin'],function(){
Route::get('/','YonetimController@index')->name('yonetim.index');
Route::get('cikis','YonetimController@cikis')->name('yonetim.cikis');


Route::resource('ayarlar','AyarController');
Route::resource('bloglar','BlogController');
Route::resource('kategori','KategoriController');
Route::resource('menuler','MenuController');
Route::resource('sayfalar','SayfaController');
Route::resource('hizmetler','HizmetController');
Route::resource('sliderlar','SliderController');
Route::resource('referanslar','ReferansController');
Route::resource('yazilar','YaziController');
Route::resource('anasayfaayar','AnasayfaAyarController');
Route::resource('ekip','EkipController');
Route::resource('restoranmenukategori','RestoranMenuKategoriController');
Route::resource('restoranmenu','RestoranMenuController');
Route::resource('yorumlar','YorumlarController');
Route::resource('galeri','GaleriController');
Route::resource('anasayfaayar','AnasayfaAyarController');

Route::get('kullanicilar','YonetimController@kullanicilar')->name('kullanicilar.index');
Route::get('kullaniciekle','YonetimController@kullaniciekle')->name('kullanici.ekle');
Route::post('kullanicikayit','YonetimController@kullanicikayit')->name('kullanici.kayit');
Route::get('kullaniciduzenle/{id}','YonetimController@kullaniciduzenle')->name('kullanici.duzenle');
Route::post('kullaniciguncelle/{id}','YonetimController@kullaniciguncelle')->name('kullanici.guncelle');
Route::delete('kullanicisil/{id}','YonetimController@kullanicisil')->name('kullanici.sil');
Route::get('iletisim','YonetimController@iletisim')->name('iletisim');
Route::post('iletisim','YonetimController@iletisimgonder')->name('iletisim.gonder');

//Galeri

Route::get('galeri', 'GaleriController@index')->name('galeri');
Route::post('galeri/uploadFiles', 'GaleriController@multiple_upload');
Route::delete('galeridelete/{id}', 'GaleriController@destroy')->name('foto.sil');
Route::post('galeriupdate/{id}', 'GaleriController@update')->name('foto.update');

});

Auth::routes(['register' => false]);

//Anasayfa
Route::get('/','HomeController@index')->name('anasayfa');

//Sayfalar
Route::get('sayfa/{id}/{slug}', 'HomeController@sayfa')->name('sayfa.goster');
Route::get('/iletisim', 'HomeController@iletisim')->name('iletisim.formu');
Route::get('/menuler', 'HomeController@restoranmenu')->name('menu.sayfa');
Route::get('/fotogaleri', 'HomeController@fotogaleri')->name('foto.galeri');
Route::post('iletisimformu','HomeController@iletisimformgonder')->name('iletisimformu.gondeer');
//anasayfa iletşim formu için
Route::get('anasayfailetisim','HomeController@anasayfailetisim')->name('anasayfailetisim.formu');
Route::post('anasayfaform','HomeController@anasayfaformgonder')->name('anasayfaform.gonder');




//Hizmetler
Route::get('/hizmetler','HomeController@hizmetler')->name('hizmetleri.goster');
Route::get('/hizmet/{id}/{slug}','HomeController@hizmet');

//Haberler (İcerikler)
Route::get('/yazilar','HomeController@haberler')->name('yazilar.goster');
Route::get('/yazi/{id}/{slug}','HomeController@haber');

app/RestoranMenu.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class RestoranMenu extends Model
{
    protected $table = 'restoranmenu';
    protected $guarded = [];

    public function kategorisi() {

        return $this->belongsTo('App\RestoranmenuKategori', 'kategori');
    }
}

app/Http/Controllers/RestoranMenuController.php
<?php

namespace App\Http\Controllers;

use App\RestoranMenu;
use App\RestoranmenuKategori;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class RestoranMenuController extends Controller
{

    public function index()
    {
        $menuler = RestoranMenu::all();
        return view('admin.restoranmenu.index',compact('menuler'));
    }

    public function create()
    {
        $kategoriler = RestoranmenuKategori::all();
        return view('admin.restoranmenu.create',compact('kategoriler'));
    }


    public function store(Request $request)
    {
        $this->validate(request(), array(

        'menuadi' => 'required',
        'fiyat' => 'required',
        'kategori' => 'required',
                                        ));
        $menu = new RestoranMenu();
        $menu->menuadi = request('menuadi');
        $menu->menuaciklama = request('menuaciklama');
        $menu->kategori = request('kategori');
        $menu->fiyat = request('fiyat');
        $menu->slug = str_slug (request('menuadi'));

        if (request()->hasFile('resim')) {

            $validator = Validator::make($request->all(), [
                'resim' => 'image|mimes:jpeg,png,jpg,gif,svg|max:512',
            ]);
            if (!$validator->passes()) {
                alert()
                    ->error('Foto Yüklenemedi', 'Foto Dosya Boyutu Çok Büyük')
                    ->autoClose(1000);
                return back();
            }


            if (request()->hasFile('resim')) {

                $this->validate(request(), array('resim' => 'image|mimes:png,jpg,jpeg,gif|max:2048'));

                $resim = request()->file('resim');
                $dosya_adi = time() . '.' . $resim->extension();

                if ($resim->isValid()) {

                    $hedef_klasor = 'uploads/dosyalar/menuler';
                    $dosya_yolu = $hedef_klasor . '/' . $dosya_adi;
                    $resim->move($hedef_klasor, $dosya_adi);
                    $menu->resim = $dosya_yolu;
                }
            }
        }

        $menu->save();

        if ($menu) {
            alert()
                ->success('Başarılı', 'Menü Kaydedildi')
                ->autoClose(1000);
            return back();


        } else {
            alert()
                ->error('Hata', 'Kaydedilmedi')
                ->autoClose(1000);
            return back();

        }
    }


    public function edit($id)
    {
        $menu = RestoranMenu::find($id);
        $kategoriler = RestoranmenuKategori::where('id','!=', $menu->kategori)->get();
        return view('admin.restoranmenu.edit', compact('menu','kategoriler'));
    }


    public function update(Request $request, $id)
    {
        $this->validate(request(), array(

            'menuadi' => 'required',
            'fiyat' => 'required',
            'kategori' => 'required',
        ));
        $menu = RestoranMenu::find($id);
        $menu->menuadi = request('menuadi');
        $menu->menuaciklama = request('menuaciklama');
        $menu->kategori = request('kategori');
        $menu->fiyat = request('fiyat');
        $menu->slug = str_slug (request('menuadi'));

        if (request()->hasFile('resim')) {

            $validator = Validator::make($request->all(), [
                'resim' => 'image|mimes:jpeg,png,jpg,gif,svg|max:512',
            ]);
            if (!$validator->passes()) {
                alert()
                    ->error('Foto Yüklenemedi', 'Foto Dosya Boyutu Çok Büyük')
                    ->autoClose(1000);
                return back();
            }


            if (request()->hasFile('resim')) {

                $this->validate(request(), array('resim' => 'image|mimes:png,jpg,jpeg,gif|max:2048'));

                $resim = request()->file('resim');
                $dosya_adi = time() . '.' . $resim->extension();

                if ($resim->isValid()) {

                    $hedef_klasor = 'uploads/dosyalar/menuler';
                    $dosya_yolu = $hedef_klasor . '/' . $dosya_adi;
                    $resim->move($hedef_klasor, $dosya_adi);
                    $menu->resim = $dosya_yolu;
                }
            }
        }

        $menu->save();

        if ($menu) {
            alert()
                ->success('Başarılı', 'Menü Güncellendi')
                ->autoClose(1000);
            return back();


        } else {
            alert()
                ->error('Hata', 'Güncellenmedi')
                ->autoClose(1000);
            return back();

        }
    }


    public function destroy($id)
    {
        $sil = RestoranMenu::destroy($id);
        if ($sil) {
            alert()
                ->success('Başarılı','Menü Silindi')
                ->autoClose(1000);
            return back();


        }else {
            alert()
                ->error('Hata','Menü Silinmedi')
                ->autoClose(1000);
            return back();

        }
    }
}

resources/views/admin/restoranmenu/create.blade.php
@extends('admin/template')
@section('icerik')

    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
                    <h5>Menü Ekle</h5>
                </div>

                <div class="widget-content nopadding">
                    {!! Form::open(['route'=>'restoranmenu.store','method'=>'POST','class'=>'form-horizontal','files'=>'true']) !!}

                    <div class="control-group">
                        <label class="control-label">Kategori Seçin</label>
                        <div class="controls">
                            <select name="kategori" class="span11">

                                @foreach($kategoriler as $kategori)

                                    <option value="{{$kategori->id}}">{{$kategori->restoranmenu_kategori}}</option>


                                @endforeach

                            </select>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Menü Adı</label>
                        <div class="controls">
                            <input type="text" class="span11" name="menuadi"/>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Menü Açıklama</label>
                        <div class="controls">
                            <textarea name="menuaciklama" class="span11" required></textarea>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Menü Resmi</label>
                        <div class="controls">
                            <input type="file" class="span11" name="resim"/>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Menü Fiyatı (TL)</label>
                        <div class="controls">
                            <input width="20" type="number" min="1" max="9999" step="any"  name="fiyat" class="span11" required>
                        </div>
                    </div>
                    <div class="form-actions">
                        <button type="submit" class="btn btn-success">İçerik Ekle</button>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>

        </div>

    </div>

@endsection

@section('css')

@endsection

@section('js')
    <script src="/admin/tinymce/js/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({ selector:'textarea' });</script>

@endsection

resources/views/admin/restoranmenu/edit.blade.php
@extends('admin/template')
@section('icerik')

    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
                    <h5>Menü Düzenle : {{$menu->menuadi}}</h5>
                </div>

                <div class="widget-content nopadding">
                    {!! Form::model($menu,['route'=>['restoranmenu.update',$menu->id],'method'=>'PUT','class'=>'form-horizontal','files'=>'true'])!!}

                    <div class="control-group">
                        <label class="control-label">Menü Kategorisi</label>
                        <div class="controls">
                            <select name="kategori" class="span11">
                                <option value="{{$menu->kategorisi->id}}" selected>{{$menu->kategorisi->restoranmenu_kategori}}</option>
                                @foreach($kategoriler as $kategori)

                                    <option value="{{$kategori->id}}">{{$kategori->restoranmenu_kategori}}</option>


                                @endforeach

                            </select>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Menü Adı</label>
                        <div class="controls">
                            <input type="text" class="span11" name="menuadi" value="{{$menu->menuadi}}"/>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Menü Fiyatı TL</label>
                        <div class="controls">
                            <input width="20" type="number" min="1" max="9999" step="any"  name="fiyat" class="span11" value="{{$menu->fiyat}}" required >
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Menü Açıklama</label>
                        <div class="controls">
                            <textarea name="menuaciklama" class="span11">{!! $menu->menuaciklama !!}</textarea>
                        </div>
                    </div>


                    <div class="control-group">
                        <label class="control-label">Menü Resmi</label>
                        <div class="controls">
                            <div><img border="0" src="/{{$menu->resim}}" width="200" height="150"> </div>
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label">Resim Seç</label>
                        <div class="controls">
                            <input type="file" class="span11" name="resim"/>
                        </div>
                    </div>
                    <div class="form-actions">
                        <button type="submit" class="btn btn-success">Menü Kaydet</button>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>

        </div>

    </div>

@endsection

@section('css')

@endsection

@section('js')
    <script src="/admin/tinymce/js/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({ selector:'textarea' });</script>

@endsection

resources/views/admin/restoranmenu/index.blade.php
@extends('admin/template')
@section('icerik')
    <div style="float:left;margin:15px 0 5px 0;"><a href="{{route('yazilar.create')}}" class="btn btn-success">Yeni Menü</a></div>
    <div style="clear:both;"></div>
    <div class="widget-box">
        <div class="widget-title"> <span class="icon"><i class="icon-th"></i></span>
            <h5>Menüler</h5>
        </div>
        <div class="widget-content nopadding">
            <table class="table table-bordered data-table">
                <thead>
                <tr>
                    <th width="20%">Görsel</th>
                    <th>Menu</th>
                    <th width="5%">Fiyat</th>
                    <th width="5%">Düzenle</th>
                    <th width="5%">Sil</th>
                </tr>
                </thead>
                <tbody>

                @foreach($menuler as $menu)

                    <tr class="gradeX">
                        <td><img height="150px" width="200px" src="/{{$menu->resim}}"></td>
                        <td><strong>{{$menu->menuadi}}</strong></br>{!! $menu->menuaciklama !!}</td>
                        <td>{{$menu->fiyat}}</td>
                        <td class="center"><a href="{{route('restoranmenu.edit',$menu->id)}}" class="btn btn-success btn-mini">Düzenle</a></td>

                        {!! Form::model($menu,['route'=>['restoranmenu.destroy',$menu->id],'method'=>'DELETE']) !!}

                        <td class="center">

                            <button type="submit" onclick="return window.confirm('Silmek istediğinize eminmisiniz?');" class="btn btn-danger btn-mini">Sil</button>

                        </td>

                        {!! Form::close() !!}

                    </tr>

                @endforeach


                </tbody>
            </table>
        </div>
    </div>

    {{--	<form action="{{route('kategoriler.destroy',$kategori->id)}}" method="DELETE">
        {{csrf_field()}}
    </form>--}}

@endsection

@section('css')
    <link rel="stylesheet" href="/admin/css/uniform.css" />
    <link rel="stylesheet" href="/admin/css/select2.css" />
@endsection

@section('js')
    <script src="/admin/js/excanvas.min.js"></script>
    <script src="/admin/js/jquery.min.js"></script>
    <script src="/admin/js/jquery.ui.custom.js"></script>
    <script src="/admin/js/bootstrap.min.js"></script>

    <script src="/admin/js/jquery.dataTables.min.js"></script>
    <script src="/admin/js/matrix.tables.js"></script>

@endsection




{{--
@extends ('admin/template')

@section('icerik')
    <div style="float:right; margin: 15px 0 5px 0;"><a href="{{route('yazilar.create')}}" class="btn btn-success"> İçerik Ekle</a></div>
    <div style="clear:both;"></div>
    <div class="widget-box">
        <div class="widget-title"> <span class="icon"><i class="icon-th"></i></span>
            <h5>Blog Yönetimi</h5>
        </div>
        <div class="widget-content nopadding">
            <table class="table table-bordered data-table">
                <thead>
                <tr>
                    <th>Yazı Başlık</th>
                    <th>Kategori</th>
                    <th>Yazar</th>
                    <th>Düzenle</th>
                    <th>Sil</th>
                </tr>
                </thead>
                <tbody>
                @foreach($yazilar as $yazi)
                    <tr class="gradeX">
                        <td>{{$yazi->baslik}}</td>
                        <td>
                            {{$yazi->kategorisi->baslik}}

                        </td>
                        <td>{{$yazi->kullanici->name}}</td>
                        <td class="center"><a href="{{route('yazilar.edit', $yazi->id)}}"class="btn btn-success btn-mini">Düzenle</a> </td>

                        {!! Form::model($yazi,['route'=>['yazilar.destroy',$yazi->id],'method'=>'DELETE']) !!}
                        <td class="center">
                            <button type="submit" class="btn btn-danger btn-mini">Sil</button>
                        </td>

                        {!! Form::close() !!}
                    </tr>

                @endforeach

                </tbody>
            </table>
        </div>
    </div>


@endsection

@section('css')
    <link rel="stylesheet" href="/admin/css/uniform.min.css" />
    <link rel="stylesheet" href="/admin/css/select2.css" />

@endsection

@section('js')
    <script src="/admin/js/excanvas.min.js"></script>
    <script src="/admin/js/jquery.min.js"></script>
    <script src="/admin/js/jquery.ui.custom.js"></script>
    <script src="/admin/js/bootstrap.min.js"></script>

    <script src="/admin/js/jquery.dataTables.min.js"></script>
    <script src="/admin/js/matrix.tables.js"></script>
@endsection--}}