routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});
Route::group(['prefix'=>'yonetim','middleware' =>'admin'],function(){
Route::get('/','YonetimController@index')->name('yonetim.index');
Route::get('cikis','YonetimController@cikis')->name('yonetim.cikis');


Route::resource('ayarlar','AyarController');
Route::resource('bloglar','BlogController');
Route::resource('kategori','KategoriController');
Route::resource('menuler','MenuController');
Route::resource('sayfalar','SayfaController');
Route::resource('hizmetler','HizmetController');
Route::resource('sliderlar','SliderController');
Route::resource('referanslar','ReferansController');
Route::resource('yazilar','YaziController');
Route::resource('anasayfaayar','AnasayfaAyarController');
Route::resource('ekip','EkipController');
Route::resource('restoranmenukategori','RestoranMenuKategoriController');
Route::resource('restoranmenu','RestoranMenuController');
Route::resource('yorumlar','YorumlarController');
Route::resource('galeri','GaleriController');
Route::resource('anasayfaayar','AnasayfaAyarController');

Route::get('kullanicilar','YonetimController@kullanicilar')->name('kullanicilar.index');
Route::get('kullaniciekle','YonetimController@kullaniciekle')->name('kullanici.ekle');
Route::post('kullanicikayit','YonetimController@kullanicikayit')->name('kullanici.kayit');
Route::get('kullaniciduzenle/{id}','YonetimController@kullaniciduzenle')->name('kullanici.duzenle');
Route::post('kullaniciguncelle/{id}','YonetimController@kullaniciguncelle')->name('kullanici.guncelle');
Route::delete('kullanicisil/{id}','YonetimController@kullanicisil')->name('kullanici.sil');
Route::get('iletisim','YonetimController@iletisim')->name('iletisim');
Route::post('iletisim','YonetimController@iletisimgonder')->name('iletisim.gonder');

//Galeri

Route::get('galeri', 'GaleriController@index')->name('galeri');
Route::post('galeri/uploadFiles', 'GaleriController@multiple_upload');
Route::delete('galeridelete/{id}', 'GaleriController@destroy')->name('foto.sil');
Route::post('galeriupdate/{id}', 'GaleriController@update')->name('foto.update');

});

Auth::routes(['register' => false]);

//Anasayfa
Route::get('/','HomeController@index')->name('anasayfa');

//Sayfalar
Route::get('sayfa/{id}/{slug}', 'HomeController@sayfa')->name('sayfa.goster');
Route::get('/iletisim', 'HomeController@iletisim')->name('iletisim.formu');
Route::get('/menuler', 'HomeController@restoranmenu')->name('menu.sayfa');
Route::get('/fotogaleri', 'HomeController@fotogaleri')->name('foto.galeri');
Route::post('iletisimformu','HomeController@iletisimformgonder')->name('iletisimformu.gondeer');
//anasayfa iletşim formu için
Route::get('anasayfailetisim','HomeController@anasayfailetisim')->name('anasayfailetisim.formu');
Route::post('anasayfaform','HomeController@anasayfaformgonder')->name('anasayfaform.gonder');




//Hizmetler
Route::get('/hizmetler','HomeController@hizmetler')->name('hizmetleri.goster');
Route::get('/hizmet/{id}/{slug}','HomeController@hizmet');

//Haberler (İcerikler)
Route::get('/yazilar','HomeController@haberler')->name('yazilar.goster');
Route::get('/yazi/{id}/{slug}','HomeController@haber');

resources/views/admin/iletisimformu.blade.php
@extends ('admin/template')

@section('icerik')


    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
                    <h5>İletişim Formu</h5>
                </div>



                <div class="widget-content nopadding">
                    <form action="{{route('iletisim.gonder')}}" method="POST" class="form-horizontal">
                        {{csrf_field()}}
                  {{--  {!! Form::open(['route'=>'bloglar.store','method'=>'POST','class'=>'form-horizontal','files'=>'true']) !!}--}}


                  {{--  <div class="control-group">
                        <label class="control-label">Üst Kategori</label>
                        <div class="controls">
                            <select name="blog_ust_id" class="span11">

                                <option value="" selected>Üst Blog</option>
                                @foreach($bloglar as $blog)

                                    <option value="{{$blog->id}}">{{$blog->blog_adi}}</option>
                                @endforeach

                            </select>
                        </div>
                    </div>--}}

                    <div class="control-group">
                        <label class="control-label"> Ad Soyad</label>
                        <div class="controls">
                            <input type="text" class="span11" name="adsoyad"  />
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">E-Mail Adresi</label>
                        <div class="controls">
                            <input type="text" class="span11" name="email"  />
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label"> Mesajınız </label>
                        <div class="controls">
                            <input type="text"  class="span11" name="mesaj"  />
                        </div>
                    </div>
                  {{--  <div class="control-group">
                        <label class="control-label"> Yazı İçerik</label>
                        <div class="controls">
                            <input type="text"  class="span11" name="yazi_icerik"  />
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label"> Yazı Kategorisi</label>
                        <div class="controls">
                            <input type="text"  class="span11" name="yazi_kategorisi"  />
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label">Yazı İçin Öne Çıkan Foto Ekle</label>
                        <div class="controls">
                            <input type="file" name="blog_foto" id="blog_foto" class="span11"  />
                        </div>
                    </div>--}}
                    <div class="form-actions">
                        <button type="submit" class="btn btn-success">Formu Gönder </button>
                    </div>
                    </form>
                   {{-- {!! Form::close() !!}--}}
                </div>
            </div>

        </div>

    </div>

@endsection

@section('css')

@endsection

@section('js')

@endsection

resources/views/admin/index.blade.php
@extends('admin.template')

@section('icerik')

    <!--Action boxes-->
    <div class="container-fluid">
        <div class="quick-actions_homepage">
            <ul class="quick-actions">
                <li class="bg_lb"> <a href="{{route('sayfalar.create')}}"> <i class="icon-plus-sign"></i> Sayfa Ekle</a> </li>
                <li class="bg_lg"> <a href="{{route('yazilar.create')}}"> <i class="icon-plus-sign"></i>Yeni Haber</a> </li>
                <li class="bg_ly"> <a href="{{route('galeri')}}"> <i class="icon-plus-sign"></i>Galeri </a> </li>
                <li class="bg_lo"> <a href="{{route('ekip.create')}}"> <i class="icon-plus-sign"></i>Yeni Ekip</a> </li>
                <li class="bg_ls"> <a href="{{route('restoranmenu.create')}}"> <i class="icon-plus-sign"></i> Yiyecek Menü Ekle</a> </li>
                <li class="bg_lb"> <a href="{{route('anasayfaayar.index')}}"> <i class="icon-certificate"></i> Anasayfa Ayarları</a> </li>


            </ul>
        </div>
        <!--End-Action boxes-->

        <div class="container-fluid">

        <div class="row-fluid">
            <!--İstatistik-->
            <div class="span6">
            <div class="widget-box">
                <div class="widget-title bg_lg"><span class="icon"><i class="icon-signal"></i></span>
                    <h5>Site İstatistik</h5>
                </div>
                <div class="widget-content" >
                    <div class="row-fluid">

                        <div class="span12">
                            <ul class="site-stats">
                                <li class="bg_lb"> <strong>{{$sayfacount}}</strong> <small>Sayfa</small></li>
                                <li class="bg_ly"> <strong>{{$galericount}}</strong> <small>Fotoğraf</small></li>
                                <li class="bg_lg"> <strong>{{$habercount}}</strong> <small>Haber</small></li>
                                <li class="bg_ls"> <strong>{{$restoranmenucount}}</strong> <small>Restoran Menü</small></li>

                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            </div>
            <!--İstatistik-->

            <!--Son Haberler-->
            <div class="span6">
            <div  class="widget-box">
                <div  class="widget-title bg_lo"  data-toggle="collapse" href="#collapseG3" > <span class="icon icon-paper-clip"> <i class="icon-chevron-down"></i> </span>
                    <h5>  Son Haberler</h5>
                </div>

                @foreach ($lastnews as $haber)
                    <div class="new-update clearfix">
                        <i class="icon-gift"></i>
                        <span class="update-notice">
                        <a title="" href="#"><strong>{{$haber->baslik}} </strong></a>
                        <span>{!! str_limit(strip_tags($haber->icerik ),$limit=200,$end='...') !!}</span> </span>
                    </div>
                @endforeach
            </div>
            </div>
            <!--Son Haberler-->

        </div>
        <div class="row-fluid">
            <!--İstatistik-->
            <div class="span6">
                <div class="widget-box">
                    <div  class="widget-title bg_lo"  data-toggle="collapse" href="#collapseG3" > <span class="icon icon-paper-clip"> <i class="icon-chevron-down"></i> </span>
                        <h5>  Son Yorumlar</h5>
                    </div>

                    @foreach ($yorumlar as $yorum)
                        <div class="new-update clearfix">
                            <i class="icon-gift"></i>
                            <span class="update-notice">
                        <a title="" href="#"><strong>{{$yorum->ad}} </strong></a>
                        <span>{!! str_limit(strip_tags($yorum->yorum ),$limit=200,$end='...') !!}</span> </span>
                        </div>
                    @endforeach
                </div>
            </div>
            <!--İstatistik-->

            <!--Son Haberler-->
            <div class="span6">
                <div  class="widget-box">
                    <div  class="widget-title bg_lo"  data-toggle="collapse" href="#collapseG3" > <span class="icon icon-paper-clip"> <i class="icon-chevron-down"></i> </span>
                        <h5>  Son Haberler</h5>
                    </div>

                    @foreach ($menuler as $menu)
                        <div class="new-update clearfix">
                            <i class="icon-gift"></i>
                            <span class="update-notice">
                        <a title="" href="#"><strong>{{$menu->menuadi}} : Fiyat {{$menu->fiyat}} {{$ayar->parabirimi}}</strong></a>
                        <span>{!! str_limit(strip_tags($menu->menuaciklama ),$limit=200,$end='...') !!}</span> </span>
                        </div>
                    @endforeach
                </div>
            </div>
            <!--Son Haberler-->

        </div>
    </div>
    </div>

@endsection


@section('css')

@endsection

@section('js')

@endsection

resources/views/admin/notification.blade.php
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-notify/0.2.0/js/bootstrap-notify.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-notify/0.2.0/css/bootstrap-notify.css">

<div class='notifications top-right'></div>


<script>


    @if(Session::has('success'))

    $('.top-right').notify({

        message: { text: "{{ Session::get('success') }}" }

    }).show();

    @php

        Session::forget('success');

    @endphp

    @endif


    @if(Session::has('info'))

    $('.top-right').notify({

        message: { text: "{{ Session::get('info') }}" },

        type:'info'

    }).show();

    @php

        Session::forget('info');

    @endphp

    @endif


    @if(Session::has('warning'))

    $('.top-right').notify({

        message: { text: "{{ Session::get('warning') }}" },

        type:'warning'

    }).show();

    @php

        Session::forget('warning');

    @endphp

    @endif


    @if(Session::has('error'))

    $('.top-right').notify({

        message: { text: "{{ Session::get('error') }}" },

        type:'danger'

    }).show();

    @php

        Session::forget('error');

    @endphp

    @endif


</script>

resources/views/admin/template.blade.php
 <!DOCTYPE html>
<html lang="en">
<head>
    <title>{{$ayar->site_adi}}</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="/admin/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/admin/css/bootstrap-responsive.min.css" />
    <link rel="stylesheet" href="/admin/css/fullcalendar.css" />
    <link rel="stylesheet" href="/admin/css/matrix-style.css" />
    <link rel="stylesheet" href="/admin/css/matrix-media.css" />
    <link href="/admin/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" href="/admin/css/jquery.gritter.css" />
    @yield('css')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.6.9/sweetalert2.min.css">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css'>

</head>
<body>

<!--Header-part-->
<div id="header">
    <h1><a href="/">Tag </a></h1>
</div>
<!--close-Header-part-->


<!--top-Header-menu-->
<div id="user-nav" class="navbar navbar-inverse">
    <ul class="nav">
        <li  class="dropdown" id="profile-messages" ><a title="" href="#" data-toggle="dropdown" data-target="#profile-messages" class="dropdown-toggle"><i class="icon icon-user"></i>  <span class="text"> Merhaba, {{Auth::user()->name}} </span><b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><a target="_blank" href="{{route('anasayfa')}}"><i class="icon-user"></i>Web Sitesi</a></li>
                <li><a href="{{route('kullanici.duzenle',Auth::user()->id)}}"><i class="icon-user"></i> Profilim</a></li>

                <li class="divider"></li>
                <li><a href="{{route('yonetim.cikis')}}"><i class="icon-key"></i> Çıkış</a></li>
            </ul>
        </li>

    </ul>
</div>
<div id="sidebar">
    <ul>
        <li ><a href="{{route('yonetim.index')}}"><i class="icon icon-home"></i> <span>Panel Anasayfa</span></a> </li>

        <li class="submenu" > <a href="#"><i class="icon icon-wrench"></i> <span>Ayarlar </span><span class="label label-important">2</span></a>
            <ul>
                <li><a href="{{route('ayarlar.index')}}">Site Ayarları</a></li>
                <li><a href="{{route('anasayfaayar.index')}}">Anasayfa Ayarları</a></li>
             </ul>
         </li>

        <li> <a href="{{route('sayfalar.index')}}"><i class="icon icon-paper-clip"></i> <span>Sayfa Yönetimi </span></a> </li>
        {{--<li> <a href="{{route('hizmetler.index')}}"><i class="icon icon-star"></i> <span>Hizmet Yönetimi </span></a>--}} </li>
        <li> <a href="{{route('ekip.index')}}"><i class="icon icon-group"></i> <span>Ekip Yönetimi </span></a> </li>
        <li> <a href="{{route('sliderlar.index')}}"><i class="icon icon-film"></i> <span>Slider Yönetimi </span></a> </li>
       {{-- <li> <a href="{{route('referanslar.index')}}"><i class="icon icon-briefcase"></i> <span>Referans Yönetimi </span></a> </li>--}}

        <li class="submenu" > <a href="#"><i class="icon icon-book"></i> <span>İçerik Yönetimi </span><span class="label label-important">3</span></a>
             <ul>
                    <li><a href="{{route('yazilar.create')}}">Yeni Yazı Ekle</a></li>
                    <li><a href="{{route('yazilar.index')}}">Tüm Yazılar</a></li>
                    <li><a href="{{route('kategori.index')}}">Kategori Yönetimi</a></li>
             </ul>
        </li>

        <li class="submenu" > <a href="#"><i class="icon icon-list"></i> <span>Restoran Menü Yönetimi </span><span class="label label-important">3</span></a>
            <ul>
                <li><a href="{{route('restoranmenu.create')}}">Yeni Menü Ekle</a></li>
                <li><a href="{{route('restoranmenu.index')}}">Tüm Menüler</a></li>
                <li><a href="{{route('restoranmenukategori.index')}}">Kategori Yönetimi</a></li>

            </ul>
        </li>
        <li> <a href="{{route('kullanicilar.index')}}"><i class="icon icon-user-md"></i> <span>Kullanıcı Yönetimi </span></a></li>
        <li> <a href="{{route('menuler.index')}}"><i class="icon icon-group"></i> <span>Menü Yönetimi</span></a></li>
        <li> <a href="{{route('galeri')}}"><i class="icon icon-camera"></i> <span>Foto Galeri </span></a> </li>
        <li> <a href="{{route('yorumlar.index')}}"><i class="icon icon-comments"></i> <span>Yorumlar </span></a> </li>
        <li class="bg_lr"> <a href="{{route('yonetim.cikis')}}"><i style="color: white" class="icon icon-off"></i> <span style="color: white">Çıkış </span></a> </li>



    </ul>
</div>
<!--sidebar-menu-->

<!--main-container-part-->
<div id="content">


    <!--Action boxes-->
    <div class="container-fluid">

        @yield('icerik')

        <!--End-Action boxes-->


    </div>

</div>
<div class="row-fluid">
    <div id="footer" style="color: #ffffff;" class="span12"> Tag Dijital Ajans Penel V1.0</div>
</div>
<script src="/admin/js/excanvas.min.js"></script>
<script src="/admin/js/jquery.min.js"></script>
<script src="/admin/js/jquery.ui.custom.js"></script>
<script src="/admin/js/bootstrap.min.js"></script>
<script src="/admin/js/jquery.flot.min.js"></script>
<script src="/admin/js/jquery.flot.resize.min.js"></script>
<script src="/admin/js/jquery.peity.min.js"></script>
<script src="/admin/js/fullcalendar.min.js"></script>
<script src="/admin/js/matrix.js"></script>
<script src="/admin/js/matrix.dashboard.js"></script>
<script src="/admin/js/jquery.gritter.min.js"></script>
<script src="/admin/js/matrix.interface.js"></script>
<script src="/admin/js/matrix.chat.js"></script>
<script src="/admin/js/jquery.validate.js"></script>
<script src="/admin/js/matrix.form_validation.js"></script>
<script src="/admin/js/jquery.wizard.js"></script>
<script src="/admin/js/jquery.uniform.js"></script>
<script src="/admin/js/select2.min.js"></script>
<script src="/admin/js/matrix.popover.js"></script>
<script src="/admin/js/jquery.dataTables.min.js"></script>
<script src="/admin/js/matrix.tables.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.6.9/sweetalert2.min.js"></script>

@include('sweetalert::alert')

@yield('js')


</body>
</html>