routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});
Route::group(['prefix'=>'yonetim','middleware' =>'admin'],function(){
Route::get('/','YonetimController@index')->name('yonetim.index');
Route::get('cikis','YonetimController@cikis')->name('yonetim.cikis');


Route::resource('ayarlar','AyarController');
Route::resource('bloglar','BlogController');
Route::resource('kategori','KategoriController');
Route::resource('menuler','MenuController');
Route::resource('sayfalar','SayfaController');
Route::resource('hizmetler','HizmetController');
Route::resource('sliderlar','SliderController');
Route::resource('referanslar','ReferansController');
Route::resource('yazilar','YaziController');
Route::resource('anasayfaayar','AnasayfaAyarController');
Route::resource('ekip','EkipController');
Route::resource('restoranmenukategori','RestoranMenuKategoriController');
Route::resource('restoranmenu','RestoranMenuController');
Route::resource('yorumlar','YorumlarController');
Route::resource('galeri','GaleriController');
Route::resource('anasayfaayar','AnasayfaAyarController');

Route::get('kullanicilar','YonetimController@kullanicilar')->name('kullanicilar.index');
Route::get('kullaniciekle','YonetimController@kullaniciekle')->name('kullanici.ekle');
Route::post('kullanicikayit','YonetimController@kullanicikayit')->name('kullanici.kayit');
Route::get('kullaniciduzenle/{id}','YonetimController@kullaniciduzenle')->name('kullanici.duzenle');
Route::post('kullaniciguncelle/{id}','YonetimController@kullaniciguncelle')->name('kullanici.guncelle');
Route::delete('kullanicisil/{id}','YonetimController@kullanicisil')->name('kullanici.sil');
Route::get('iletisim','YonetimController@iletisim')->name('iletisim');
Route::post('iletisim','YonetimController@iletisimgonder')->name('iletisim.gonder');

//Galeri

Route::get('galeri', 'GaleriController@index')->name('galeri');
Route::post('galeri/uploadFiles', 'GaleriController@multiple_upload');
Route::delete('galeridelete/{id}', 'GaleriController@destroy')->name('foto.sil');
Route::post('galeriupdate/{id}', 'GaleriController@update')->name('foto.update');

});

Auth::routes(['register' => false]);

//Anasayfa
Route::get('/','HomeController@index')->name('anasayfa');

//Sayfalar
Route::get('sayfa/{id}/{slug}', 'HomeController@sayfa')->name('sayfa.goster');
Route::get('/iletisim', 'HomeController@iletisim')->name('iletisim.formu');
Route::get('/menuler', 'HomeController@restoranmenu')->name('menu.sayfa');
Route::get('/fotogaleri', 'HomeController@fotogaleri')->name('foto.galeri');
Route::post('iletisimformu','HomeController@iletisimformgonder')->name('iletisimformu.gondeer');
//anasayfa iletşim formu için
Route::get('anasayfailetisim','HomeController@anasayfailetisim')->name('anasayfailetisim.formu');
Route::post('anasayfaform','HomeController@anasayfaformgonder')->name('anasayfaform.gonder');




//Hizmetler
Route::get('/hizmetler','HomeController@hizmetler')->name('hizmetleri.goster');
Route::get('/hizmet/{id}/{slug}','HomeController@hizmet');

//Haberler (İcerikler)
Route::get('/yazilar','HomeController@haberler')->name('yazilar.goster');
Route::get('/yazi/{id}/{slug}','HomeController@haber');

resources/views/admin/referanslar/create.blade.php
@extends ('admin/template')

@section('icerik')


    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
                    <h5> Referans Ekle</h5>
                </div>



                <div class="widget-content nopadding">
                    {!! Form::open(['route'=>'referanslar.store','method'=>'POST','class'=>'form-horizontal','files'=>'true']) !!}




                    <div class="control-group">
                        <label class="control-label"> Referans adı</label>
                        <div class="controls">
                            <input type="text" class="span11" name="referans_adi"  />
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label"> Firma Adı</label>
                        <div class="controls">
                            <input type="text" class="span11" name="firma_adi"  />
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label"> Referans Açıklama</label>
                        <div class="controls">
                            <input type="text" class="span11" name="referans_aciklama"  />
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label"> Referans  Fotoğrafı</label>
                        <div class="controls">
                            <input type="file" name="referans_gorseli"  class="span11"  />
                        </div>
                    </div>
                    <div class="form-actions">
                        <button type="submit" class="btn btn-success">Referans  Ekle</button>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>

        </div>

    </div>

@endsection

@section('css')

@endsection


@section('js')
    <script src="/adminkurumsal/tinymce/js/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({ selector:'textarea' });</script>
@endsection

resources/views/admin/referanslar/edit.blade.php
@extends ('admin/template')

@section('icerik')


    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
                    <h5> Referans Düzenle : {{$referans->referans_adi}}</h5>
                </div>



                <div class="widget-content nopadding">
                    {!! Form::model($referans,(['route'=>['referanslar.update',$referans->id],'method'=>'PUT','class'=>'form-horizontal','files'=>'true'])) !!}




                    <div class="control-group">
                        <label class="control-label"> Referans Adı</label>
                        <div class="controls">
                            <input type="text" class="span11" name="referans_adi" value="{{$referans->referans_adi}}"  />
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label"> Firma Adı</label>
                        <div class="controls">
                            <input type="text" class="span11" name="firma_adi" value="{{$referans->firma_adi}}"  />
                          {{--  <textarea name="firma_adi" class="span11">{!! $referans->firma_adi !!}</textarea>--}}
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label"> Referans Açıklama</label>
                        <div class="controls">
                            <input type="text" class="span11" name="referans_aciklama" value="{{$referans->referans_aciklama}}"  />
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label"> Referans Kapak Görseli</label>
                        <div class="controls">
                            <input type="file" name="referans_gorseli"  class="span11"  />
                        </div>
                        <div><img width="300px" src="/{{$referans->referans_gorseli}}"></div>
                    </div>
                    <div class="form-actions">
                        <button type="submit" class="btn btn-success">Referans Güncelle</button>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>

        </div>

    </div>

@endsection

@section('css')

@endsection


@section('js')
    <script src="/adminkurumsal/tinymce/js/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({ selector:'textarea' });</script>
@endsection

resources/views/admin/referanslar/index.blade.php
@extends ('admin/template')

@section('icerik')
    <div style="float:right; margin: 15px 0 5px 0;"><a href="{{route('referanslar.create')}}" class="btn btn-success">Referans Ekle</a></div>
    <div style="clear:both;"></div>
    <div class="widget-box">
        <div class="widget-title"> <span class="icon"><i class="icon-th"></i></span>
            <h5>Referans Yönetimi</h5>
        </div>
        <div class="widget-content nopadding">
            <table class="table table-bordered data-table">
                <thead>
                <tr>
                    <th>Referans Adı</th>
                    <th>Firma Adı</th>
                    <th>Referans Açıklama</th>
                    <th width="5%">Düzenle</th>
                    <th width="5%">Sil</th>
                </tr>
                </thead>
                <tbody>
                @foreach($referanslar as $referans)
                    <tr class="gradeX">
                        <td>{{$referans->referans_adi}}</td>
                        <td>

{!! str_limit(strip_tags($referans->firma_adi),$limit=100,$end='...') !!}

                        </td>

                        <td>{{$referans->referans_aciklama}}</td>

                        <td class="center"><a href="{{route('referanslar.edit', $referans->id)}}"class="btn btn-success btn-mini">Düzenle</a> </td>

                        {!! Form::model($referans,['route'=>['referanslar.destroy',$referans->id],'method'=>'DELETE']) !!}
                        <td class="center">
                            <button type="submit" onclick="return window.confirm('Silmek istediğinize eminmisiniz?');" class="btn btn-danger btn-mini">Sil</button>
                        </td>

                        {!! Form::close() !!}
                    </tr>

                @endforeach

                </tbody>
            </table>
        </div>
    </div>


@endsection

@section('css')
    <link rel="stylesheet" href="/adminkurumsal/css/uniform.min.css" />
    <link rel="stylesheet" href="/adminkurumsal/css/select2.css" />

@endsection

@section('js')
    <script src="/adminkurumsal/js/excanvas.min.js"></script>
    <script src="/adminkurumsal/js/jquery.min.js"></script>
    <script src="/adminkurumsal/js/jquery.ui.custom.js"></script>
    <script src="/adminkurumsal/js/bootstrap.min.js"></script>

    <script src="/adminkurumsal/js/jquery.dataTables.min.js"></script>
    <script src="/adminkurumsal/js/matrix.tables.js"></script>
@endsection